version: '3.5'

services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    image: gateway
    ports:
      - 50052:50052
      - 8080:8080
    depends_on: 
      - order
      - user
      - cart
      - product

  order:
    build:
      context: .
      dockerfile: ./order/Dockerfile
    container_name: order
    image: order
    environment:
      PG_URL: 'postgres://postgres:root@order_postgres:5432/postgres?sslmode=disable'
    ports:
      - 50051:50051
    depends_on:
      order_postgres:
        condition: service_healthy

  user:
    build:
      context: .
      dockerfile: ./user/Dockerfile
    container_name: user
    image: user
    environment:
      PG_URL: 'postgres://postgres:root@user_postgres:5432/postgres?sslmode=disable'
    ports:
      - 50053:50053
    depends_on:
      user_postgres:
        condition: service_healthy

  cart:
    build:
      context: .
      dockerfile: ./cart/Dockerfile
    container_name: cart
    image: cart
    environment:
      REDIS_URL: 'redis://cart_redis:6379/0'
      PG_URL: 'postgres://postgres:root@cart_postgres:5432/postgres?sslmode=disable'
    ports:
      - 50054:50054
    depends_on:
      cart_postgres:
        condition: service_healthy
      cart_redis:
        condition: service_healthy

  product:
    build:
      context: .
      dockerfile: ./product/Dockerfile
    container_name: product
    image: product
    environment:
      REDIS_URL: 'redis://product_redis:6379/0'
      PG_URL: 'postgres://postgres:root@product_postgres:5432/postgres?sslmode=disable'
    ports:
      - 50055:50055
    depends_on:
      product_postgres:
        condition: service_healthy
      product_redis:
        condition: service_healthy

  order_postgres:
    container_name: order_pg_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - order-pg-data:/var/lib/postgresql/data
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 10

  user_postgres:
    container_name: user_pg_db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - user-pg-data:/var/lib/postgresql/data
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 10

  cart_postgres:
    container_name: cart_pg_db
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - cart-pg-data:/var/lib/postgresql/data
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 10

  cart_redis:
    container_name: cart_redis_db
    image: redis:7.2.3-alpine3.18
    volumes:
      - cart-redis-data:/data
    ports:
      - 6379:6379
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 10

  product_postgres:
    container_name: product_pg_db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - product-pg-data:/var/lib/postgresql/data
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 10

  product_redis:
    container_name: product_redis_db
    image: redis:7.2.3-alpine3.18
    volumes:
      - product-redis-data:/data
    ports:
      - 6380:6379
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  order-pg-data: 
    name: order-pg-data

  user-pg-data: 
    name: user-pg-data

  cart-redis-data:
    name: cart-redis-data

  cart-pg-data:
    name: cart-pg-data

  product-pg-data:
    name: product-pg-data

  product-redis-data:
    name: product-redis-data
