// Code generated by MockGen. DO NOT EDIT.
// Source: cart/internal/infrastructure/interfaces/cart_task.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	model "github.com/Go-Marketplace/backend/cart/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockCartTaskRepo is a mock of CartTaskRepo interface.
type MockCartTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCartTaskRepoMockRecorder
}

// MockCartTaskRepoMockRecorder is the mock recorder for MockCartTaskRepo.
type MockCartTaskRepoMockRecorder struct {
	mock *MockCartTaskRepo
}

// NewMockCartTaskRepo creates a new mock instance.
func NewMockCartTaskRepo(ctrl *gomock.Controller) *MockCartTaskRepo {
	mock := &MockCartTaskRepo{ctrl: ctrl}
	mock.recorder = &MockCartTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartTaskRepo) EXPECT() *MockCartTaskRepoMockRecorder {
	return m.recorder
}

// CreateCartTask mocks base method.
func (m *MockCartTaskRepo) CreateCartTask(ctx context.Context, task model.CartTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCartTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCartTask indicates an expected call of CreateCartTask.
func (mr *MockCartTaskRepoMockRecorder) CreateCartTask(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCartTask", reflect.TypeOf((*MockCartTaskRepo)(nil).CreateCartTask), ctx, task)
}

// GetCartTasks mocks base method.
func (m *MockCartTaskRepo) GetCartTasks(ctx context.Context, to int64) ([]*model.CartTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartTasks", ctx, to)
	ret0, _ := ret[0].([]*model.CartTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartTasks indicates an expected call of GetCartTasks.
func (mr *MockCartTaskRepoMockRecorder) GetCartTasks(ctx, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartTasks", reflect.TypeOf((*MockCartTaskRepo)(nil).GetCartTasks), ctx, to)
}
