// Code generated by MockGen. DO NOT EDIT.
// Source: product/internal/usecase/product.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	dto "github.com/Go-Marketplace/backend/product/internal/api/grpc/dto"
	model "github.com/Go-Marketplace/backend/product/internal/model"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIProductUsecase is a mock of IProductUsecase interface.
type MockIProductUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIProductUsecaseMockRecorder
}

// MockIProductUsecaseMockRecorder is the mock recorder for MockIProductUsecase.
type MockIProductUsecaseMockRecorder struct {
	mock *MockIProductUsecase
}

// NewMockIProductUsecase creates a new mock instance.
func NewMockIProductUsecase(ctrl *gomock.Controller) *MockIProductUsecase {
	mock := &MockIProductUsecase{ctrl: ctrl}
	mock.recorder = &MockIProductUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductUsecase) EXPECT() *MockIProductUsecaseMockRecorder {
	return m.recorder
}

// CreateDiscount mocks base method.
func (m *MockIProductUsecase) CreateDiscount(ctx context.Context, discount model.Discount) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiscount", ctx, discount)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDiscount indicates an expected call of CreateDiscount.
func (mr *MockIProductUsecaseMockRecorder) CreateDiscount(ctx, discount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiscount", reflect.TypeOf((*MockIProductUsecase)(nil).CreateDiscount), ctx, discount)
}

// CreateProduct mocks base method.
func (m *MockIProductUsecase) CreateProduct(ctx context.Context, product model.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockIProductUsecaseMockRecorder) CreateProduct(ctx, product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockIProductUsecase)(nil).CreateProduct), ctx, product)
}

// DeleteDiscount mocks base method.
func (m *MockIProductUsecase) DeleteDiscount(ctx context.Context, productID uuid.UUID) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiscount", ctx, productID)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDiscount indicates an expected call of DeleteDiscount.
func (mr *MockIProductUsecaseMockRecorder) DeleteDiscount(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiscount", reflect.TypeOf((*MockIProductUsecase)(nil).DeleteDiscount), ctx, productID)
}

// DeleteProduct mocks base method.
func (m *MockIProductUsecase) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockIProductUsecaseMockRecorder) DeleteProduct(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockIProductUsecase)(nil).DeleteProduct), ctx, id)
}

// GetAllCategories mocks base method.
func (m *MockIProductUsecase) GetAllCategories(ctx context.Context) ([]*model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCategories", ctx)
	ret0, _ := ret[0].([]*model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCategories indicates an expected call of GetAllCategories.
func (mr *MockIProductUsecaseMockRecorder) GetAllCategories(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCategories", reflect.TypeOf((*MockIProductUsecase)(nil).GetAllCategories), ctx)
}

// GetCategory mocks base method.
func (m *MockIProductUsecase) GetCategory(ctx context.Context, id int32) (*model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", ctx, id)
	ret0, _ := ret[0].(*model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockIProductUsecaseMockRecorder) GetCategory(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockIProductUsecase)(nil).GetCategory), ctx, id)
}

// GetProduct mocks base method.
func (m *MockIProductUsecase) GetProduct(ctx context.Context, id uuid.UUID) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, id)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockIProductUsecaseMockRecorder) GetProduct(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockIProductUsecase)(nil).GetProduct), ctx, id)
}

// GetProducts mocks base method.
func (m *MockIProductUsecase) GetProducts(ctx context.Context, searchParams dto.SearchProductsDTO) ([]*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProducts", ctx, searchParams)
	ret0, _ := ret[0].([]*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockIProductUsecaseMockRecorder) GetProducts(ctx, searchParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockIProductUsecase)(nil).GetProducts), ctx, searchParams)
}

// UpdateProduct mocks base method.
func (m *MockIProductUsecase) UpdateProduct(ctx context.Context, product model.Product) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, product)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockIProductUsecaseMockRecorder) UpdateProduct(ctx, product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockIProductUsecase)(nil).UpdateProduct), ctx, product)
}

// UpdateProducts mocks base method.
func (m *MockIProductUsecase) UpdateProducts(ctx context.Context, products []model.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProducts", ctx, products)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProducts indicates an expected call of UpdateProducts.
func (mr *MockIProductUsecaseMockRecorder) UpdateProducts(ctx, products interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProducts", reflect.TypeOf((*MockIProductUsecase)(nil).UpdateProducts), ctx, products)
}
