app:
  name: 'cart_service'
  version: '0.1.0'

grpc:
  host: cart
  port: 50054

redis:
  redis_url: 'redis://cart_redis:6379/0'

postgres:
  dialect: 'postgres'
  pool_max: 10
  pg_url: 'postgres://postgres:root@cart_postgres:5432/postgres?sslmode=disable'

worker:
  cart_ttl: 5m
  cart_task_worker_interval: 1s

logger:
  log_level: 'debug'
