app:
  name: 'product_service'
  version: '0.1.0'

grpc:
  host: product
  port: 50055

redis:
  redis_url: 'redis://product_redis:6379/0'

postgres:
  dialect: 'postgres'
  pool_max: 10
  pg_url: 'postgres://postgres:root@product_postgres:5432/postgres?sslmode=disable'

logger:
  log_level: 'debug'
