name: Lint
on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
          go-version-file: go.mod
        env:
          GOPATH: ${{ github.workspace }}/go

      - name: Run linter
        run: make lint
