name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
          go-version-file: go.mod
          cache-dependency-path: go.sum
        env:
          GOPATH: ${{ github.workspace }}/go

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: make test

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
