// Code generated by MockGen. DO NOT EDIT.
// Source: order/internal/usecase/order.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	dto "github.com/Go-Marketplace/backend/order/internal/api/grpc/dto"
	model "github.com/Go-Marketplace/backend/order/internal/model"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIOrderUsecase is a mock of IOrderUsecase interface.
type MockIOrderUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIOrderUsecaseMockRecorder
}

// MockIOrderUsecaseMockRecorder is the mock recorder for MockIOrderUsecase.
type MockIOrderUsecaseMockRecorder struct {
	mock *MockIOrderUsecase
}

// NewMockIOrderUsecase creates a new mock instance.
func NewMockIOrderUsecase(ctrl *gomock.Controller) *MockIOrderUsecase {
	mock := &MockIOrderUsecase{ctrl: ctrl}
	mock.recorder = &MockIOrderUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOrderUsecase) EXPECT() *MockIOrderUsecaseMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockIOrderUsecase) CreateOrder(ctx context.Context, order *model.Order) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, order)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockIOrderUsecaseMockRecorder) CreateOrder(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockIOrderUsecase)(nil).CreateOrder), ctx, order)
}

// CreateOrderline mocks base method.
func (m *MockIOrderUsecase) CreateOrderline(ctx context.Context, orderline *model.Orderline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderline", ctx, orderline)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrderline indicates an expected call of CreateOrderline.
func (mr *MockIOrderUsecaseMockRecorder) CreateOrderline(ctx, orderline interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderline", reflect.TypeOf((*MockIOrderUsecase)(nil).CreateOrderline), ctx, orderline)
}

// DeleteOrder mocks base method.
func (m *MockIOrderUsecase) DeleteOrder(ctx context.Context, orderID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrder", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrder indicates an expected call of DeleteOrder.
func (mr *MockIOrderUsecaseMockRecorder) DeleteOrder(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrder", reflect.TypeOf((*MockIOrderUsecase)(nil).DeleteOrder), ctx, orderID)
}

// DeleteOrderline mocks base method.
func (m *MockIOrderUsecase) DeleteOrderline(ctx context.Context, orderID, productID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderline", ctx, orderID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderline indicates an expected call of DeleteOrderline.
func (mr *MockIOrderUsecaseMockRecorder) DeleteOrderline(ctx, orderID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderline", reflect.TypeOf((*MockIOrderUsecase)(nil).DeleteOrderline), ctx, orderID, productID)
}

// DeleteUserOrders mocks base method.
func (m *MockIOrderUsecase) DeleteUserOrders(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserOrders", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserOrders indicates an expected call of DeleteUserOrders.
func (mr *MockIOrderUsecaseMockRecorder) DeleteUserOrders(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserOrders", reflect.TypeOf((*MockIOrderUsecase)(nil).DeleteUserOrders), ctx, userID)
}

// GetOrder mocks base method.
func (m *MockIOrderUsecase) GetOrder(ctx context.Context, orderID uuid.UUID) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, orderID)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockIOrderUsecaseMockRecorder) GetOrder(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockIOrderUsecase)(nil).GetOrder), ctx, orderID)
}

// GetOrderline mocks base method.
func (m *MockIOrderUsecase) GetOrderline(ctx context.Context, orderID, productID uuid.UUID) (*model.Orderline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderline", ctx, orderID, productID)
	ret0, _ := ret[0].(*model.Orderline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderline indicates an expected call of GetOrderline.
func (mr *MockIOrderUsecaseMockRecorder) GetOrderline(ctx, orderID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderline", reflect.TypeOf((*MockIOrderUsecase)(nil).GetOrderline), ctx, orderID, productID)
}

// GetOrders mocks base method.
func (m *MockIOrderUsecase) GetOrders(ctx context.Context, searchParams dto.SearchOrderDTO) ([]*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, searchParams)
	ret0, _ := ret[0].([]*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockIOrderUsecaseMockRecorder) GetOrders(ctx, searchParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockIOrderUsecase)(nil).GetOrders), ctx, searchParams)
}

// UpdateOrderline mocks base method.
func (m *MockIOrderUsecase) UpdateOrderline(ctx context.Context, orderline *model.Orderline) (*model.Orderline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderline", ctx, orderline)
	ret0, _ := ret[0].(*model.Orderline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderline indicates an expected call of UpdateOrderline.
func (mr *MockIOrderUsecaseMockRecorder) UpdateOrderline(ctx, orderline interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderline", reflect.TypeOf((*MockIOrderUsecase)(nil).UpdateOrderline), ctx, orderline)
}
